### ISSUE TITLE
Print cuts off text.

### ISSUE THREAD

**Issue by mhwice** [notaapp/talk#116]
When printing a document, long sentences are being cut off on the right side. 

To illustrate this issue, when in the Print Menu I changed the export format to "Open In Preview" so I could screenshot it. 

<img width="960" alt="nota-print-issue" src="https://user-images.githubusercontent.com/19433287/135726868-524ef51f-9271-4d5a-ade2-0a5f9447b250.png">

And here is what the document should look like.

<img width="960" alt="nota-preview" src="https://user-images.githubusercontent.com/19433287/135727105-44c6036d-538f-4873-97b9-825dca923859.png">

I am running: Nota Version 0.33.0 (Intel)

**Comment by astoilkov** [comment]
Hmm. I can't replicate the problem. 

Can you open Print click Show Details and make a screenshot of the options?

Does this happen with all your files or just this specific one?

Thanks in advance.

**Comment by astoilkov** [comment]
I will close this issue because I can't replicate it. We've also made a change that could possibly fix this problem.

However, if someone experiences it and can provide more information (preferably a file I can replicate it with) I will reopen it.
