### ISSUE TITLE
Command-click to toggle todo status

### ISSUE THREAD

**Issue by trevormeier** [notaapp/talk#132]
Hi there—just trying out Nota for the first time. I'm loving it!

Would it make sense to enable command-click to toggle todo item status? This would be consistent with the command-click URL behaviour (i.e. command-click to enable an expected "non-markdown" function). I find I'm often going through todo lists with the mouse, and not the keyboard so some kind of mouse action would be useful.

Thanks!

**Comment by astoilkov** [comment]
Hi.

The next release of Nota will render todo lists as checkboxes in "Hide Markdown" mode. Clicking on the todo item will toggle it (no need to hold command).

Will this behavior work for you?

**Comment by trevormeier** [comment]
That’s a nice touch! It’s a compromise but it can work for me
