### ISSUE TITLE
Feature Request: Supprt x-callback URLs (like for Things3)

### ISSUE THREAD

**Issue by minthemiddle** [notaapp/talk#133]
On the latest version of Nota, using x-callback URLs such as `things:///show?id=DoMm74H6694nhbX3pSnJMK` results in unclickable links. Using this outside of Nota (e.g. in HTML > Firefox) leads you to open the Things app with the linked task. It would be nice if Nota supported x-callback URLs as well.

**Comment by astoilkov** [comment]
Yes, we should definitely support that. We will try to do this soon. Thanks!

**Comment by astoilkov** [comment]
We implemented this. The next release of Nota will include the feature.

**Comment by astoilkov** [comment]
This now works in 0.35. Thanks!
