### ISSUE TITLE
Feature request - Simpler/faster way to save a new file

### ISSUE THREAD

**Issue by dvcrn** [notaapp/talk#137]
Coming from obsidian or other editors like iA Writer, nota has a lot of steps needed for saving a file

1. CMD-N and type some stuff
2. Hit CMD-S
3. Select the folder in the dialog
4. Type in the name of the file or hit enter while it's selected in the sidebar

Those extra steps are feel-able when tabbing into Nota to rapidly take some notes

This also keeps re-opening the sidebar for me to confirm the filename, even when in editor-only mode which is a bit distracting. (I also have the heading-filename experiment on, so the additional step to confirm the name feels even more unnecessary)

As an idea:
Allow specifying of a default location (like an Inbox, or just the root). When hitting CMD-S (or even fully automatic without manual save), just save to that location with the default filename, that is anyway identical to the first H1 the first time even without experiment

**Comment by astoilkov** [comment]
Cool you are mentioning this. This is what we have been working on recently. The next release will include something very close to your idea.

**Comment by dvcrn** [comment]
Awesome 😄 looking forward to the new version

**Comment by astoilkov** [comment]
@dvcrn Have you experimented with the new way to create new files? What do you think?

**Comment by astoilkov** [comment]
We've improved on that in the last 2 releases. We will improve it even more in the next releases. Closing this because it looks older given the new functionality. If you feel we can improve more, feel free to create a new discussion.
