### ISSUE TITLE
Feature Request: Duplicate File

### ISSUE THREAD

**Issue by minthemiddle** [notaapp/talk#143]
I have template markdowns that I duplicate every day, e.g. daily logs and diary entries.
Right now, I have to right-click on a file in the file browser, click on "copy", then click somewhere and hit "paste".

Instead, it would be nice to have a **command** in the **command palette** that says **"Duplicate file"**.
Right now, there is only "Duplicate line" (on line level) and delete or move file (on file level).

**Comment by astoilkov** [comment]
Do you imagine "Duplicate File" to work like "Move File To..." (to ask you in which folder to duplicate the file into)?

Btw, have you considered a [custom command](https://nota.md/docs/custom-commands.html) or in your case the folder where you want to put the duplicated file is always different?

Also, we are considering a templating feature where you can place `_template.md` file into a folder and then New File in that folder will use that template. Will this work for you?

**Comment by minthemiddle** [comment]
> Do you imagine "Duplicate File" to work like "Move File To..." (to ask you in which folder to duplicate the file into)

Good point. I thought about "Duplicate in the folder where you are" as this is what I expect to happen.

**Comment by minthemiddle** [comment]
> Btw, have you considered a custom command or in your case the folder where you want to put the duplicated file is always different?

I can solve my need with a custom command. I did not look into that before. Thanks!

**Comment by astoilkov** [comment]
> Good point. I thought about "Duplicate in the folder where you are" as this is what I expect to happen.

For "Duplicate in the folder where you are" you can do ⌘C and then ⌘V and this will make a duplicate — just like in Finder.
