### ISSUE TITLE
Search results are not complete

### ISSUE THREAD

**Issue by minthemiddle** [notaapp/talk#147]
Internal search results do not show all notes that contain a search term.

Example:

- I use the tag `#app`
- I search for `#app`
- In my alphabetical folders, I know there are results in `N`
- In the search, the results are sorted by A-Z
- The last results I get are from `D`
- This confirmed my impression that search is often not exhausive

![Screenshot_22-02-02__10_57](https://user-images.githubusercontent.com/1950766/152132711-fb3b30b3-7629-45bb-ab8e-7e1686179a53.png)

**Comment by astoilkov** [comment]
Yes, you are right. The 0.35 release will include major improvements to the search. We've already fixed this as well.

**Comment by astoilkov** [comment]
We now handle this better in 0.35. Closing this issue.
