### ISSUE TITLE
Not possible to edit markdown of images

### ISSUE THREAD

**Issue by dvcrn** [notaapp/talk#153]
When inserting a image into nota I can't manage to figure out how to edit it's image tag (or alt). Even when "Show Markdown" enabled, the image always renders inline and never in Markdown form 

Optimal solution: Render inline, but return to markdown form when the cursor is on the image

**Comment by astoilkov** [comment]
Yes, you are right. We've now changed that and the next version will show the image markdown instead of the image preview when Show Markdown is enabled.

**Comment by astoilkov** [comment]
Regarding the optimal solution, I agree. We should do that in the future.

**Comment by apg-dev** [comment]
Not that this is an ideal solution, but if you place the cursor to the left of the image and type a random character, the image will transform back into markdown where you can make any desired edits and then remove the temp random character.

**Comment by dvcrn** [comment]
Yeah that's a very sub-optimal solution 😄

**Comment by astoilkov** [comment]
We now render the Markdown syntax when you select View → Show Markdown and this way you can edit. We are planning to make it possible to edit the Markdown while the image is in preview mode but that's for another release. 

Closing this issue.
