### ISSUE TITLE
Images don't update when renaming the linked file

### ISSUE THREAD

**Issue by dvcrn** [notaapp/talk#154]
Steps to reproduce: 

1. Insert an image, it gets imported into nota
2. Rename the image file in nota
3. The image still renders fine within nota in the imported document
4. Restart Nota
5. The image no longer renders because the path changed

Nota looks like it's already updating links to files when a file is renamed (or at least does for backlinks), would be nice if it can do that too for images

**Comment by astoilkov** [comment]
This is a bug. I've already fixed it. The next release will include the fix.

Thanks for reporting, it helps a lot!

**Comment by astoilkov** [comment]
This is now part of the 0.35 release. Closing this issue. Thanks!
