### ISSUE TITLE
Folder called "root"

### ISSUE THREAD

**Issue by borekb** [notaapp/talk#166]
Small thing but Nota uses the word "root" to signify the workspace folder, which can get a bit weird if I create a standard folder called `root`.

<img width="262" alt="Screen Shot 2022-03-06 at 22 28 27" src="https://user-images.githubusercontent.com/101152/156942937-60182ad6-7a4a-43d4-948c-b290e9d2e095.png">

**Comment by astoilkov** [comment]
Hmm. Yes, that makes sense. We will see what we can do about this. Thanks!

**Comment by astoilkov** [comment]
What do you think about the new design we introduced? I think it removed the confusion around the root folder. Do you agree? Thanks!

**Comment by borekb** [comment]
I agree, the icons help a lot. Thanks!
