### ISSUE TITLE
Backlinks with a stop . in them do not work

### ISSUE THREAD

**Issue by nianiam** [notaapp/talk#171]
If I have a file named 'Next.js', backlinks [[Next.js]] will not recognise the file and appear red. Other punctuation works fine.

**Comment by astoilkov** [comment]
That's a bug. We fixed it and the next release will include the fix. Thanks!

**Comment by astoilkov** [comment]
This is now fixed in Nota 0.35. Closing this issue. Thanks for reporting it!
