### ISSUE TITLE
The Quote command should also add `>` to empty lines

### ISSUE THREAD

**Issue by borekb** [notaapp/talk#173]
I keep hitting this slight issue so I'd like to transfer it from the original report https://github.com/careteditor/issues/issues/610:

---

Sample Markdown at the beginning:

```
Example

quote
```

After I apply the quote formatting:

```
> Example

> quote
```

which renders like this in preview:

![image](https://user-images.githubusercontent.com/101152/34946232-5eb93302-fa06-11e7-882e-3590e1b55dd1.png)

I'd prefer this result:

```
> Example
>
> quote
```

which renders like this:

![image](https://user-images.githubusercontent.com/101152/34946250-6f229fb2-fa06-11e7-933b-515ebdab8d3f.png)

**Comment by astoilkov** [comment]
After only four years 😃, we improved the Format → Quote command and now this and other issues have been fixed. Thank you for nudging us, Borek!
