### ISSUE TITLE
Pipe wiki link not behaving as expected

### ISSUE THREAD

**Issue by minthemiddle** [notaapp/talk#175]
Nota v0.3.4 introduced piped wiki links, such as `[[note|title]]`.
It does not, however, behave as expected (using 0.34.3)

When I add a title with the pipe, the link shows red (which according to release notes shows a missing link). The link works, however. Expected would be: no red color.

When I add title with the pipe, even in "Do not show Markdown" mode, both note and title are shown in the preview. Expected would be: only show title.

<img width="570" alt="pipe-link" src="https://user-images.githubusercontent.com/1950766/161226628-ee704046-46c0-4125-a061-18a9b12524e9.png">

**Comment by astoilkov** [comment]
This is a bug and a feature request. We've actually fixed and implemented both in the next release. The next release will be available in 1-2 weeks.

**Comment by astoilkov** [comment]
This is now part of the 0.35 release. Closing this issue. Thanks!
