### ISSUE TITLE
How to debug frequent crashes on tags addition/editing

### ISSUE THREAD

**Issue by minthemiddle** [notaapp/talk#176]
When adding tags in Nota notes (0.34.3 (Intel), Catalina 10.15.7 (19H15)), I get very frequent crashes. Approximately, every 10th time, I add or edit a tag, so very often. Neither of the two options on the error message make any difference with regard to error frequency.

I cannot see a pattern nor replicate, it just happens.
How can I help you debug the problem?

<img width="659" alt="Bildschirmfoto 2022-04-01 um 12 17 19" src="https://user-images.githubusercontent.com/1950766/161244853-3aa8706d-2c35-49f8-b2a1-cf28fae30240.png">

**Comment by astoilkov** [comment]
I fixed the issue. The next release will include the fix.

**Comment by minthemiddle** [comment]
Wow, that's great! I'm sorry that I could not give more context.

**Comment by astoilkov** [comment]
No problem. If we need more information next time, I will explain to you where you can find the Nota.log file.

**Comment by astoilkov** [comment]
This should no longer be an issue in the latest release. Closing this.
