### ISSUE TITLE
Numbers are transformed incorrectly in unordered lists

### ISSUE THREAD

**Issue by borekb** [notaapp/talk#183]
See this video:

https://user-images.githubusercontent.com/101152/161699426-ec3c8d9b-2ac7-4ebd-a0db-7366d2474e74.mov

Alt: in an unordered list, I want to write "4. 4." (a date) but Nota transforms it to "4. 1." and changes font which indicates that it probably detects that as kind of an ordered list.

Try to write this Markdown to reproduce:

```md
- 4. 4.
```

**Comment by astoilkov** [comment]
I fixed the issue with the numbering. However, the styling will remain the same as this is part of the Markdown specification and we've never made an exception so far. Markdown specification says `- 4. 4.` is a list item with two nested ordered lists.

**Comment by borekb** [comment]
> Markdown specification says `- 4. 4.` is a list item with two nested ordered lists.

Oh, I didn't realize that it could be and then it's my mistake – I should have written that differently. Interesting!

**Comment by astoilkov** [comment]
No problem. It's an edge case in the specification. I think the spec is debatable in this case.

**Comment by astoilkov** [comment]
This now works correctly in the 0.35 release. Thanks!
