### ISSUE TITLE
How to use save hook?

### ISSUE THREAD

**Issue by minthemiddle** [notaapp/talk#186]
I just updated to v0.35.0 and learnt about save hooks from the changelog.
What I want to do: When the note saves, add a newline to the bottom of the file with an update text.

How can I create save hooks?

What did I try that failed?
- Create `save.sh` in `workspace/.nota/hooks`
- Add the following Bash

```bash
#!/bin/bash
echo date +"Updated at: %y-%m-%d, %H:%M"
```

I also tried the following

```bash
#!/bin/bash
# @parameters file
echo date +"Updated at: %y-%m-%d, %H:%M" >> @parameters
```

But that throws an error:

`/.nota/hooks/save.sh: line 3: @parameters: Read-only file system`

**Comment by astoilkov** [comment]
Sorry, we haven't published the docs for the save hook yet.
```ts
#!/bin/bash

# @parameters file

# $1 points to the path of the file that was saved

# you can do something like
echo date +"Updated at: %y-%m-%d, %H:%M" >> $1
```

**Comment by astoilkov** [comment]
Hey @minthemiddle, did you succeed in creating a save hook?

**Comment by minthemiddle** [comment]
@astoilkov Yes, could get my first auto git commit save hook running:

```bash
#!/bin/bash
# saved as LIBRARY/.nota/hooks/save.sh

# @parameters file

# $1 points to the path of the file that was saved

# you can do something like
stamp=$(date +"%Y%m%d%H%M%S")
cd "LIBRARY PATH" # could not get relative path working yet
git add .
git commit -m "Update: $stamp"
```

**Comment by astoilkov** [comment]
Cool. We are also using the save hook for the same thing!
