### ISSUE TITLE
Links don't update when using non-wiki links

### ISSUE THREAD

**Issue by dvcrn** [notaapp/talk#187]
Steps to reproduce: 

1. Create 2 documents
2. Turn off wiki links in settings
3. Insert a link using `[]()` from one document to the other
4. Rename the other document

Link is updating fine using wikilinks, but not using normal markdown links

**Comment by astoilkov** [comment]
Fixed. Sorry for the inconvinience. Will make a new release soon. Just want to look at the drag & drop bug as well.

**Comment by astoilkov** [comment]
This is now part of the latest release. Closing this issue. And again, thank you for helping us with these reports!
