### ISSUE TITLE
Feature request: Autocomplete for images 

### ISSUE THREAD

**Issue by dvcrn** [notaapp/talk#188]
If in a document and typing `![something](./foo`, it would be lovely if nota could autocomplete the image (or file path) for me 

Even better if I could specify a default behavior to use absolute path or relative path in settings for what to insert

**Comment by astoilkov** [comment]
We already support this. This is actually a bug. We will release a fix soon.

**Comment by astoilkov** [comment]
This is now part of the latest release. Closing this issue. Thanks for reporting!
