### ISSUE TITLE
[0.35] Drag & Drop of images into nota no longer works

### ISSUE THREAD

**Issue by dvcrn** [notaapp/talk#189]
Noticed that I can no longer drop images into Nota, this includes:

- Images directly into a document
- Images into the file tree 

Copy-paste does still work and imports the file correctly into the specified attachments folder

**Comment by astoilkov** [comment]
Hmm. We can't seem to replicate the problem. I will list some things that can help figure it out:
- Can you send your workspace config `.nota/config.ini` file? Maybe something there makes a difference.
- Did this work for you in 0.34?
- Can you record a video showing how it doesn't work? Sometimes there is something in the context that we're missing.

**Comment by dvcrn** [comment]
Hrrmm today it works so might have been just a glitch. I'm closing this for now
