### ISSUE TITLE
Feature request: Relative attachments folder

### ISSUE THREAD

**Issue by dvcrn** [notaapp/talk#190]
This is inspired by Obsidian, but currently Nota can only specify a fixed attachments folder. It would be nice if this could be set relative to something like:

- Set to absolute folder
- Set to folder named 'xxx' in current folder
- Put attachment in current folder

So if I had it on 'attachments' and I'm at /blog/, it would create `blog/attachments/` when a new attachment gets inserted

**Comment by astoilkov** [comment]
We are definitely considering this. Not 100% sure but I think we will implement it soon.

This seems like a duplicate of https://github.com/notaapp/talk/issues/123. I'm closing this.
