### ISSUE TITLE
Feature Request: Navigate between files with shortcuts

### ISSUE THREAD

**Issue by minthemiddle** [notaapp/talk#192]
It would be nice to navigate between files with shortcuts within the selected folder.
Right now, you can only navigate with the mouse.

[FsNotes](https://github.com/glushchenko/fsnotes) uses Vim binding (`Cmd+j`, `Cmd+k`), though that is also confusing as vim uses that within a file not a folder.

Maybe expand your [emacs shortcuts](https://nota.md/docs/emacs-shortcuts.html) (I'm not familiar with emacs, but dired seems to be a file editor mode).

**Comment by astoilkov** [comment]
Have you tried doing ⌘⇧E (Select Active File in File Bar) and then using arrow keys or emacs shortcuts?

Otherwise, we could also add commands for moving up/down while the sidebar isn't focused and just not assign default shortcuts.

**Comment by minthemiddle** [comment]
I did not know about `cmd+shift+e` + keys, that already works for me.

**Comment by erusev** [comment]
You can also use `cmd-esc` for the same thing.
