### ISSUE TITLE
Bug: Cannot use ' as a hotkey

### ISSUE THREAD

**Issue by Overload119** [notaapp/talk#203]
1. Use Alt+[ or Alt+] as a hotkey to move-left right

![CleanShot 2022-04-25 at 08 57 26](https://user-images.githubusercontent.com/1012072/165127245-fb7c20de-1c76-40b3-92e1-903fc073df89.png)

2. It leaves behind a symbol each time you switch tabs.

https://user-images.githubusercontent.com/1012072/165127297-c13931bc-06c5-43e8-86b1-9918bff906e1.mp4

**Comment by astoilkov** [comment]
Fixed. The next release will include the fix. Sorry for the inconvenience.

**Comment by astoilkov** [comment]
This is now fixed in the latest 0.36 release. Closing this issue. Thanks!
