### ISSUE TITLE
Mac Press-and-hold for entering characters with diacritics doesn't work properly.

### ISSUE THREAD

**Issue by Auratelience** [notaapp/talk#211]
Instead of entering a single character (ie `é`, it enters a normal character when the key is first pressed, and then the accented char afterwards (giving the result: `eé`).
Thanks, Auratelience

**Comment by astoilkov** [comment]
Hi. This was a bug in 0.34. We fixed it in 0.35. Can you check what version of Nota you are running?

**Comment by astoilkov** [comment]
@Auratelience Did you have time to check? Thanks!

**Comment by Auratelience** [comment]
Hi Antonio, yes I'm on version 0.35.4. Sorry for the late reply.

𝐴𝑢𝑟𝑎𝑡𝑒𝑙𝑖𝑒𝑛𝑐𝑒

**Comment by astoilkov** [comment]
@Auratelience I can't seem to replicate the issue. Maybe I'm missing something contextual. What type of Input source are you using? Here's a video of what I'm experiencing. Any ideas on how to replicate it would be useful.

![CleanShot 2022-05-07 at 17 32 15](https://user-images.githubusercontent.com/884810/167258731-78c5c166-65ac-4ebf-8147-16e676b88839.gif)

**Comment by astoilkov** [comment]
I found the problem. Disregard the last message. Thanks!

**Comment by Auratelience** [comment]
Hi Antonio, the solution I have found is to use an app called Espanso, which lets me enter all these characters much faster.

𝐴𝑢𝑟𝑎𝑡𝑒𝑙𝑖𝑒𝑛𝑐𝑒

**Comment by astoilkov** [comment]
This is now fixed in the latest 0.36 release. Closing this issue. Thanks for reporting!
