### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by davistech** [notaapp/talk#212]
This may have been requested before, but it would be very helpful to have code folding at headings and list items available. Examples include: Obsidian, Marked 2, MMComposer5, and others.

**Comment by astoilkov** [comment]
It seems you forgot about it but you've requested this previously — [Feature Request: Add section folding to the editor](https://github.com/notaapp/talk/issues/81). The good news is that we've already started working on this. We have a private experiment that we're experimenting with. However, it's not a trivial feature to implement so it may take us a little while before we ship it.

I will close this issue in favor of the original.

**Comment by astoilkov** [comment]
Thank you! Those are very kind words that make working on Nota a very pleasant experience for us! Keep the issues going.
