### ISSUE TITLE
Feature request: support for CJK (and other full-width character languages)

### ISSUE THREAD

**Issue by yeefom** [notaapp/talk#226]
Hi,

Thanks for making this amazing software! 

Currently Nota doesn't properly support CJK (and presumably other languages using full-width characters). For example punctuation marks such as period and comma can be incorrectly placed in the beginning of a line as shown in the picture.

<img width="700" alt="nota" src="https://user-images.githubusercontent.com/13666363/168724661-c5da8e5f-ca25-45a2-b7a1-e12f949447cb.png">

**Comment by astoilkov** [comment]
I've started working on this. I will update you when I have progress on this. Hoping to fix this today.

Thanks for posting!

**Comment by yeefom** [comment]
Amazing! Look forward to the new release

**Comment by astoilkov** [comment]
Done. The new release is now available.

Closing this issue.
