### ISSUE TITLE
Accessibility: File Tree 

### ISSUE THREAD

**Issue by Overload119** [notaapp/talk#23]
It took me a minute to understand the way the file tree displays photos.
I would suggest we respect the names of the folders that the user has specified instead of lowercasing it, which makes it look different at first glance.
And using the typical characters associated with subdirectories (`/` instead of `>`)

![image](https://user-images.githubusercontent.com/1012072/95480320-9f4b4800-0940-11eb-8f8d-207fa332c5c9.png)

**Comment by erusev** [comment]
> I would suggest we respect the names of the folders that the user has specified instead of lowercasing it

I agree, I think we can do this.

> using the typical characters associated with subdirectories

A lot of apps use "›" as a path delimiter, including Finder (in View › Show Path Bar). It creates more space between segments which hopefully makes the whole path a bit easier to read.

Do you have specific scenarios where "›" is an issue?

Thanks!

**Comment by astoilkov** [comment]
We now respect the name of the folders.

The › delimiter is common in other apps. We also use it everywhere in the app when showing paths and probably we won't change that.

Closing this issue.
