### ISSUE TITLE
Feature Request: Markdown highlight support

### ISSUE THREAD

**Issue by chadkoh** [notaapp/talk#231]
As a user, I would like to highlight text using double `==` signs, common in TFT apps like Obsidian. For example:

> In this sentence ==this is highlighted text==.

As an initial pass, the highlighted text can be rendered with a yellow background.

**Comment by astoilkov** [comment]
Hmm. Nota supports this. See the screenshot below:
<img width="828" alt="CleanShot 2022-05-25 at 13 37 58@2x" src="https://user-images.githubusercontent.com/884810/170243550-94d50ce3-dd15-4f5c-bdff-677b46c1629d.png">

**Comment by chadkoh** [comment]
Apologies. User error!
