### ISSUE TITLE
Strange search behavior

### ISSUE THREAD

**Issue by borekb** [notaapp/talk#232]
I've got a `.md` note that contains this:

```markdown
# GitHub tips

_Search terms: PM, project management, tips, tricks, hacks, GitHub, projects._

... etc. etc. ...
```

In the following video, I do this:

1. Press Cmd-P
2. Type "github tricks" → doesn't find good results 🚫
3. Delete the last "s" (the search string is now "github trick") → finds a good result ✅
4. Type "s" again (the search string is now "github tricks") → keeps showing the good result ✅

As if the speed at which I typed mattered or something.

https://user-images.githubusercontent.com/101152/170492673-f62e1926-f0da-4f07-b30d-39c2b87b21fa.mov

**Comment by astoilkov** [comment]
> As if the speed at which I typed mattered or something.

If you type the query slowly, does the search term appear?

**Comment by borekb** [comment]
No, that theory was wrong.

Here's a much slower video, hopefully it gives you some hints:


https://user-images.githubusercontent.com/101152/170650398-25f4be16-936c-4405-a23b-1dc99725a155.mov

**Comment by astoilkov** [comment]
This is fixed in the latest release.

Closing this issue.
