### ISSUE TITLE
Feature Request: Search via CLI

### ISSUE THREAD

**Issue by minthemiddle** [notaapp/talk#238]
To integrate Nota even better in workflows outside of Nota (e.g. Alfred/Raycast), it would be very helpful if the CLI of Nota would support search.

Example:

`nota search SEARCH_TERM`

I have a special use case for this:
I'm giving unique IDs to every note, such as `7HUEiU4c`. With a search via CLI, I could get to the desired note very quickly also from outside of Nota (=Alfred, in my case). Right now, I have to open Nota first, open the search and find it there. 

I'm sure that there are other use cases

**Comment by astoilkov** [comment]
Quick question. Does `nota search` shows Nota and open the search dialog with the `SEARCH_TERM` filled?

**Comment by astoilkov** [comment]
Also. Is the global search shortcut work for you?
![CleanShot 2022-05-31 at 11 17 07@2x](https://user-images.githubusercontent.com/884810/171126374-d0b8c8eb-c718-40a1-98e1-0a5f24134102.png)

**Comment by minthemiddle** [comment]
Global key works for this use case.
