### ISSUE TITLE
Multi-selection of note resets list position to first selected

### ISSUE THREAD

**Issue by rjp** [notaapp/talk#253]
To reproduce: 

1. Have a notebook with enough notes to require scrolling (I have 78 in INBOX atm.)
2. Select any note.
3. Scroll to another note such that the first is off the screen.
4. cmd-click to multi-select.
5. List shifts position to show what seems to be "the last position that isn't where we are now" (originally thought it was "first selected" but it seems a bit more complex.)

What should happen: List should never shift position without user scrolling.

This is a bit of a hassle when you've got a long list and you're trying to select a bunch that are scattered around.

**Comment by astoilkov** [comment]
Thanks. Will fix this soon.

**Comment by astoilkov** [comment]
The fix is now part of the latest 0.38 release.

Closing this issue. Thanks for reporting!
