### ISSUE TITLE
Opening files outside of the workspace 

### ISSUE THREAD

**Issue by qazzym** [notaapp/talk#261]
I have run into an issue where I open a markdown file that is not in my workspace (on the Desktop, for example) for a one-off edit and Nota is not already running. When I do this Nota will open but the file itself will not until I click on it again. Is this an issue or an intended behaviour?

**Comment by astoilkov** [comment]
This is a bug. I will look into this. Thanks!

**Comment by astoilkov** [comment]
This is now fixed in the 0.38 release.

@qazzym You can test it to verify. Thank you for your contributions. It makes a difference!

Closing this issue.
