### ISSUE TITLE
Checkboxes in lists randomly un-check themselves

### ISSUE THREAD

**Issue by davidaayers** [notaapp/talk#267]
I haven't been able to reliable re-produce, but I'm noticing that since the most recent release, tasks will un-check themselves. I've noticed it most consistently when copying and pasting a task that's been marked complete, but it appears to happen at other times. I use tasks heavily in my Nota workflow, so it's becoming quite inconvenient.

To be clear, when I'm referring to tasks, I'm using this syntax in Markdown:

`- [ ] Some task goes here`

Which renders as:

<img width="232" alt="image" src="https://user-images.githubusercontent.com/10705/180257086-9118c4d5-32af-405c-b007-f1347cdbe86a.png">

**Comment by astoilkov** [comment]
Ok. I found the problem. No need to answer. The next release will include a fix.

Sorry for the inconvenience 😞.

**Comment by davidaayers** [comment]
Thanks for the quick response!

**Comment by astoilkov** [comment]
The fix is now part of the latest 0.38 release.

Thank you for reporting this. It helps us a lot.

Closing this issue.
