### ISSUE TITLE
can't save draft

### ISSUE THREAD

**Issue by alex-jerechinsky** [notaapp/talk#270]
Hi. I'm using Nota version 0.37.1 (Apple Silicon). I'm running macOS Monterey 12.4.

I am unable to save a draft. 

Steps to reproduce: 
1. Create a draft ⇧⌘N
2. Try to save it ⌘S 
3. When selecting directory using Enter, nothing happens.

![can't save](https://user-images.githubusercontent.com/75733878/180601488-45e7ee19-e67d-4bcf-85f5-1857c04fc346.gif)

**Comment by astoilkov** [comment]
Hi. We fixed the bug. The next release will include a fix.

Sorry for the inconvenience 😞.

**Comment by astoilkov** [comment]
This is now fixed in the latest 0.38 release.

Closing this issue. Sorry for the big delay.
