### ISSUE TITLE
folding bug: editing any bullet point unfolds all folded bullet points

### ISSUE THREAD

**Issue by alex-jerechinsky** [notaapp/talk#271]
Please see GIF for a demonstration.

Loving Nota otherwise! ✌️❤️ 

![annoying unfolding](https://user-images.githubusercontent.com/75733878/181092485-0f9da9a5-fe7c-4977-afc4-a489bb406de1.gif)

**Comment by astoilkov** [comment]
I fixed the issue. The next release will include a fix. Thanks for reporting!

**Comment by astoilkov** [comment]
The fix is now part of the new 0.38 release.

I'm closing this issue. Thank you for reporting this! It helps a lot.
