### ISSUE TITLE
Unable to Switch Theme in Dark Mode

### ISSUE THREAD

**Issue by qazzym** [notaapp/talk#294]
There seems to be a bug where it doesn't seem possible to switch theme while I am using Nota dark mode and macOS is in dark mode as well. But with macOS in light mode I able to switch between Nota light and dark mode easily using the command palette.

**Comment by astoilkov** [comment]
Hmm. I can't replicate this.

Are the theme items in the command palette grayed out?

**Comment by qazzym** [comment]
Interesting. Yes, they’re grayed out. I’ll try and experiment more.

**Comment by astoilkov** [comment]
No need. I found the cause of the problem. The next release will include the fix.

**Comment by astoilkov** [comment]
The fix is part of the latest release.

Closing this issue.
