### ISSUE TITLE
Czech diacritics mess up 'expand selection' feature

### ISSUE THREAD

**Issue by alex-jerechinsky** [notaapp/talk#303]
I'm used to selecting words by double-clicking them. This bug however also messes up the 'expand selection' feature. 

It seems like Nota doesn't recognize letter characters with Czech diacritics as part of the word. Characters with diacritics such as following: `ěščřžýáíéťďň`

Gif demonstration:
![doubleclick](https://user-images.githubusercontent.com/75733878/189197339-89688267-6237-41e4-a5df-2a8714e43b25.gif)

<details>
  <summary>original text</summary>
 # 1854 Havlíček Borovský Karel - Král Lávra

## Literární druh a žánr:
satirická* alegorická* báseň (poezie, epika)

## Literární směr:
knižně poprvé vydáno r. 1870 (posmrtně); vytvořeno v době exilu v Brixenu (pol. 50. let 19. stol.) - vrchol a závěr autorovy tvorby i života; pro očividnou kritiku habsburské monarchie cenzurováno; doznívající národní obrození*

## Figury:
- anafora - opakování textu „**Král** Lávra má dlouhé oslí uši, **král** je ušatec!“
- hyperbola neboli nadsázka
- personifikace - basa rve
- epiteton konstans -
</details>

**Comment by astoilkov** [comment]
I will take a look at it very soon and try to fix it. Thanks for reporting this. Helps a lot!

**Comment by astoilkov** [comment]
I fixed the issue. The next release will include the fix.

**Comment by astoilkov** [comment]
This is now part of the latest release.

Closing this issue.
