### ISSUE TITLE
Pressing arrow-down on last line moves cursor to the beginning of line instead of end

### ISSUE THREAD

**Issue by alex-jerechinsky** [notaapp/talk#306]
Don't know if this is intentional, but when I'm on the last line and I press arrow-down, Nota will move the cursor to **the beginning of the line**. I'm used to the behavior of other text editors, which would move the cursor to the **end of the line**. 

Of course, I can use ⌘ + →, to move to the end of the line, but it would take some time for me to unlearn the behavior of other editors. 😄

**P.S**. Love Nota otherwise! Absolute game-changer of an editor for me. ❤️ ✌️ Can't wait for the multi-window (or split-screen) feature!!

Gif demonstration.
![jumptotheend](https://user-images.githubusercontent.com/75733878/189433764-acda5b87-015c-42d3-b311-bc9a18f6adcd.gif)

**Comment by astoilkov** [comment]
I fixed the bug. The next release will include the fix.

Thanks!

**Comment by borekb** [comment]
Funny, I just created a very similar video to report this, incl. "lorem ipsum" 😄.

Good to hear it's fixed already, it a small but annoying bug.

**Comment by borekb** [comment]
It's such a small thing but so annoying 😄. Looking forward to the upcoming release.

**Comment by astoilkov** [comment]
This is now part of the latest release.

Closing this issue.
