### ISSUE TITLE
Diacritics not matched in search in Create and Search dialogs

### ISSUE THREAD

**Issue by petrbouchal** [notaapp/talk#331]
In my root folder, I have md files whose file names contain the following strings:
- RMŽ
- účel
- and lots of other files whose names do not contain these strings

Here is what I observe when I enter the strings below into the Search or Create field:
- when I type "účel", nothing matches
- when I type "ucel", nothing matches
- when I type "RMZ" or "rmz", the file with "RMŽ" in its name matches and some others based where the words start with r amd m etc.
- when I type "RMŽ" or "RMŽ", nothing matches from the moment I hit the Ž/ž key

Possibly related #303, in which case this issue will be irrelevant.

**Comment by astoilkov** [comment]
Sorry for the late response. Yeah, this is a bug. I will try to fix it for the next release.

**Comment by astoilkov** [comment]
This couldn't be fixed without implementing full support for diacritics. In the next release, typing "ucel" will find "účel".

**Comment by petrbouchal** [comment]
I feel like this was fixed in 0.39 (there's a related-sounding point in the changelog) but regressed in 0.40 - just flagging in case I remember this correctly, but it may well be that there was in fact no change in 0.39 with respect to the Create/Search dialogs.

**Comment by astoilkov** [comment]
Oops. You are right. I actually broke it recently just before both releases. I now fixed it. The next release will include it. Sorry.

**Comment by astoilkov** [comment]
This is now part of the latest release. Closing this issue.

Thanks for the feedback!
