### ISSUE TITLE
text replacement problem for some languages

### ISSUE THREAD

**Issue by gommammi** [notaapp/talk#334]
When I select a portion of text, and then type something, the normal response is that the selected text is erased, and a new text appears in that place. This is a basic expectation for any text editor app. It is not the case in Nota for some languages, for some reason (I have experienced the issue for Korean, Japanese, and Chinese).

When I type something after selecting a text, Nota responds by making the new text appear *in front of* the selected content rather than doing a text replacement. Therefore, I must first erase the selected text before entering new text in order to edit a text as I desire. 

Since I can simply take a step back and manually remove the words as intended, this might not be a serious issue. However, this is very frustrating because text substitution happens frequently in text editing apps, and this way of text replacement is so entrenched in my habit that I keep making unintended edits.

As a side note, the bug occurs based on the input language, not the selected text. For example, if I toggled "Korean" as my input language and then try to replace an English word, the problem happens.

Otherwise, I'm very pleased by the experience of using Nota as my daily markdown editing app! As I wish to stick to this app as my main editor, I'd love to see this issue being fixed at some point!

**Comment by astoilkov** [comment]
I will fix this bug today so the next release can include it.

Thanks a lot for the report!

**Comment by gommammi** [comment]
> I will fix this bug today so the next release can include it.
> 
> Thanks a lot for the report!

Thanks so much!!

**Comment by astoilkov** [comment]
Fixed. Thanks!

If you find any issues while working with these languages please let us know. We don't use them and some things like these slip by.

**Comment by astoilkov** [comment]
This is now part of the latest release.

Closing this issue.
