### ISSUE TITLE
Bug: Tables in PDF export are clipped

### ISSUE THREAD

**Issue by jxxe** [notaapp/talk#350]
Nota:
<img width="762" alt="image" src="https://user-images.githubusercontent.com/64276359/214955872-b437a53a-1932-4463-954b-a9f10e6bbfdc.png">

StackEdit:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/64276359/214955912-e218a1da-cebe-442c-b2ca-ff7c7fc77c8d.png">

It's worth checking if this applies to code blocks as well.

**Comment by astoilkov** [comment]
Did this work in the previous 0.38 release or you don't know?

**Comment by jxxe** [comment]
This was from 0.38. I just tested 0.39 and it appears to be fixed!
<img width="525" alt="image" src="https://user-images.githubusercontent.com/64276359/215037660-e07d8060-cc3b-4f65-8878-45b7cb1872b2.png">

**Comment by astoilkov** [comment]
Cool!
