### ISSUE TITLE
All headings besides H1's are not visible

### ISSUE THREAD

**Issue by GraphicOwls** [notaapp/talk#353]
Headings (not H1's) are not visible unless you are focused on that line.

![CleanShot 2023-01-27 at 13 00 32@2x](https://user-images.githubusercontent.com/30763670/215160840-7b32a4d8-0b7d-4242-9e7e-95f2d5a598e7.png)

I am focused on the h4 line which is the only time it shows. Same behavior for the others as well.
![CleanShot 2023-01-27 at 13 00 40@2x](https://user-images.githubusercontent.com/30763670/215160849-887ef00f-aa23-4cd8-8fb8-b9f2bf002a28.png)

**Comment by astoilkov** [comment]
Ouch, sorry, I fixed the bug, will make a release soon.

**Comment by GraphicOwls** [comment]
Awesome! Thank you!

**Comment by astoilkov** [comment]
The fix is now part of the latest release. Sorry for the inconvenience. Closing this issue.
