### ISSUE TITLE
Header Text Previews Disappearing

### ISSUE THREAD

**Issue by lzilioli-prism** [notaapp/talk#356]
After the 2023-01-26 update, I am seeing headers within notes randomly disappear. Described in the following video.

https://www.loom.com/share/30e1cf9a14e24e75a1de2815c19b2798

The misbehaving note's contents:

```markdown
# 2023-01-26

# 2023-01-27

some content

# Next Week Todo

some more content
```

**Comment by marlonjames71** [comment]
https://user-images.githubusercontent.com/48145861/215225659-b537d1ff-e55e-4bc8-ae43-3f0f4f4ccf3e.mp4

I'm seeing this same issue. It seems to only be happening in Daily Notes.

**Comment by astoilkov** [comment]
Ouch, sorry, I fixed the bug, will make a release soon.

**Comment by marlonjames71** [comment]
I can confirm it's fixed. Thank you @astoilkov!

**Comment by astoilkov** [comment]
Great. Sorry for the inconvenience. Closing the issue.
