### ISSUE TITLE
Editing links is hard in v0.39

### ISSUE THREAD

**Issue by klanchman** [notaapp/talk#357]
v0.39 updated how clicking a link is handled in the editor. Previously I had to Cmd+Click to follow the link, which meant I could click to drop my cursor on the link text/URL to make an edit.

Now clicking a link immediately follows it, which means it's not possible to drop my cursor right on the text/URL to start editing it. Instead, I need to drop my cursor _nearby_ and use the keyboard to get the rest of the way to what I want to edit. This is especially bad with external web links, since they take me out of Nota when I mis-click.

I'm personally used to needing to Cmd+Click to follow links in text editors. I'd love if that behavior was a preference I could set in Nota. I don't usually want to follow links when I'm editing text.

If there was at least a way not to automatically follow _external_ links, I think that might solve my main trouble with this change.

**Comment by erusev** [comment]
Hi @klanchman and thanks for sharing your thoughts on this 🙏

These are all valid points. We have a few things in mind that would improve the usability around links, and I'll see if we can fit some of them in the next release, 0.40.

In the meantime, if you have any other thoughts on the subject, I'd love to hear them 😊

**Comment by klanchman** [comment]
Thanks @erusev, I'll keep an eye out for more changes!

I think the new behavior makes sense from a standpoint of Nota becoming more of a personal knowledge base, especially for internal wiki links. It also seems like it'd go well with "Show Markdown" disabled. That's just not how I use Nota, myself. I love Nota (and previously Caret) for the great Markdown text editing experience, first and foremost! 😄

**Comment by mathewmitchell** [comment]
Ugh! I often use Markdown links to external locations. I actually don't see any way to edit those links. Placing my cursor nearby and using keyboard doesn't work for me. And, obviously, that's a really clunky approach.  Now I have to revert to another editor to write when using lots of links (which, frankly, is most of the time).

**Comment by erusev** [comment]
We're on it, will try to release a fix sometime next week.

**Comment by mathewmitchell** [comment]
Thanks so much! The way things work right now might be best for most people (I really have no idea), but even having a preferences option to fully show/edit MD links in edit mode would help so much.

**Comment by erusev** [comment]
It took us a bit longer, but we're shipping 0.40 next week that should help with this ✨ Thanks for the patience 🙏

**Comment by mathewmitchell** [comment]
Thanks so much! The change works really well for links.

**Comment by klanchman** [comment]
Thanks @erusev, I just grabbed the 0.40 update and this is working better for me 😄
