### ISSUE TITLE
Window UI problems since 0.39

### ISSUE THREAD

**Issue by minthemiddle** [notaapp/talk#366]
I'm observing multiple window UI problems since v0.39:

This happens especially, when Nota is not in full width, so for example when I add a file via an external command (Alfred, in my case) that then opens Nota (which was open before).

The close/minimize/maximize buttons are in the wrong place:
![m8k6o](https://user-images.githubusercontent.com/1950766/219938530-c18cc039-e25c-40f1-980c-d8f46e7797a4.png)

The columns are skrewed:
![k2u1d](https://user-images.githubusercontent.com/1950766/219938604-289d4c22-1edb-437b-bb87-b7ec451f9d3a.png)

Full video of UI problems:
https://www.loom.com/share/d44b57276c5349c18d22484ffb8a0217

**Comment by astoilkov** [comment]
Am I observing correctly that you've opened a lot of tabs (something like 50+) and this is happening only when there are so many tabs opened?

**Comment by minthemiddle** [comment]
@astoilkov You are right. I always have many tabs open (see [related discussion](https://github.com/notaapp/talk/discussions/364#discussion-4847854)) and when I close all of them and retry, I don't get the glitches. So yes, it must be the tabs.
