### ISSUE TITLE
Two 'toggle right sidebar' shortcuts

### ISSUE THREAD

**Issue by qazzym** [notaapp/talk#369]
There are 2 shortcuts to toggle the right sidebar, and they both seem to do the same thing. Is this a bug or am I missing a feature of one of them?

**Comment by astoilkov** [comment]
Oops, this is a bug. I fixed it. The next release will include the fix.

**Comment by astoilkov** [comment]
This is fixed in the latest release. Closing this issue.

Thanks for reporting!
