### ISSUE TITLE
Frozen shortcut symbols

### ISSUE THREAD

**Issue by qazzym** [notaapp/talk#371]
There seems to be a bug where the symbols for the 'open next tab' and 'open previous tab' are frozen at their default values, regardless of what they are changed to.

**Comment by astoilkov** [comment]
Hmm, I can't replicate this. I was able to change the shortcuts successfully. I tried with these shortcuts:
<img width="291" alt="CleanShot 2023-02-21 at 08 04 35@2x" src="https://user-images.githubusercontent.com/884810/220260967-4ac42302-9d82-4d47-9a70-5d79158db862.png">
