### ISSUE TITLE
some formatting seems not to work

### ISSUE THREAD

**Issue by mathewmitchell** [notaapp/talk#376]
I'm on Nota 40.1 with Apple Silicon. It seems that some formatting options are not working for me. For example:

- ordered lists
- highlight
- task list
- and more

If I manually type in the relevant markdown it works, but selecting some text and then choosing a format option from the menu doesn't work. Normally I type in markdown, but I wanted to highlight some text ... and that's when I noticed the problem (as I don't know the markdown shortcut).

**Comment by astoilkov** [comment]
I fixed the bug and released 0.40.2. Sorry for the inconvenience.
