### ISSUE TITLE
New file error (but possibly only on MacOS 13.3 beta)

### ISSUE THREAD

**Issue by petrbouchal** [notaapp/talk#377]
In the dialog after File > Create, I see the following

- dialog says "Create in" where previously it said "Create in root"
- once I hit enter, I get an error: "There was an error while creating the file"

If this cannot be reproduced, it is probably an issue with MacOS 13.3 beta, which I've seem cause some odd behaviour in file-opening situations in other applications. Reporting in case other come across it and/or it reappears as MacOS evolves.

**Comment by astoilkov** [comment]
I reproduced the problem and fixed it. The next release will include the fix.

**Comment by petrbouchal** [comment]
Thank you!

**Comment by petrbouchal** [comment]
Thanks for fixing this so quickly!
