### ISSUE TITLE
Request: Add option to map extra indent and outdent shortcut

### ISSUE THREAD

**Issue by klanchman** [notaapp/talk#379]
Prior to version 0.39, `Cmd+[` and `Cmd+]` behaved the same as `Shift+Tab` and `Tab`, so they'd outdent and indent the current line.

In v0.39+, `Cmd+[` and `Cmd+]` became Back/Forward. I have remapped Back/Forward, but I cannot add mappings for indent/outdent. This is an annoyance for me, because I'm used to using `Cmd+[` and `Cmd+]` to control indentation in other text editors (VS Code, Xcode, etc).

It'd be great if I could add an **extra** mapping for indent/outdent in addition to the usual `Tab` bindings.

**Comment by astoilkov** [comment]
Yeah, that makes a lot of sense. Will try to do it soon.

**Comment by astoilkov** [comment]
This is now part of the latest release.

Closing this issue.

Thanks again.
