### ISSUE TITLE
How to undo automatic naming setting

### ISSUE THREAD

**Issue by mathewmitchell** [notaapp/talk#380]
Somewhere, sometime I created a setting whereby the name I gave to the H1 of the note was also the name of the document. I'm not finding a way to undo this setting. I have a suspicion that this is a setting I created before the 0.40 update and now that custom setting is not available. At any rate, I need to no longer use this "note name" and "H1 header" to be one and the same. Any ideas how to undo this linkage?

**Comment by mathewmitchell** [comment]
Ignore above comment. Found solution under Settings > What to use as Note Title

**Comment by astoilkov** [comment]
Yeah, that's it.

Closing this issue then.
