### ISSUE TITLE
Navigating headers not working for nested headers

### ISSUE THREAD

**Issue by Overload119** [notaapp/talk#384]
Version 0.40.3 (Apple Silicon)
https://user-images.githubusercontent.com/1012072/227597452-8ed95af3-fd37-4d16-a6b9-6c0bb159c733.mp4

Click up.

**Comment by astoilkov** [comment]
I published a new release that includes a fix.

The items you are trying to click or select are disabled. We actually broke the CSS for disabled items.

Thanks!
