### ISSUE TITLE
Code block formatting "breaks" when indenting

### ISSUE THREAD

**Issue by igtsimoes** [notaapp/talk#385]
I guess the image shows the problem:

<img width="887" alt="image" src="https://user-images.githubusercontent.com/64813530/228635225-674e7d10-8d16-4a72-a9ec-9c0cab24b452.png">

**Comment by astoilkov** [comment]
I tried to fix the bug 5 days ago, committed a fix, and then reverted it because found issues with it.

I will try to fix it again soon.

**Comment by astoilkov** [comment]
I fixed it. The next release will include the fix.

In the next release, we will also ship improvements when writing code blocks in list items.

**Comment by igtsimoes** [comment]
Thank you!! 👏
