### ISSUE TITLE
Configure which files (by type) are shown in workspace sidebar

### ISSUE THREAD

**Issue by petrbouchal** [notaapp/talk#389]
My use case: I am working on a [Quarto](https://quarto.org/) project and it would be nice to have .qmd and .Rmd files (which are really souped-up markdown files) show up in the left pane. (This is a literate programming tool, but in my case most of the writing is prose so I would prefer to it in Nota rather than a programming IDE).

Currently, I think only txt and md files are shown?

Is there a way to set this? Ideally one could do this per-workspace, but a global settings would be good too. I can imagine a glob pattern to set this might be useful too, to go beyond file extensions.

Presumably there will be similar use cases with other file types and extensions.

**Comment by astoilkov** [comment]
Yeah, you are not the first one to ask for this — https://github.com/notaapp/talk/issues/50. This is important, otherwise, it makes some use cases very hard to work with. I will discuss with @erusev when we can do this.

Sorry for the late response 😔.
