### ISSUE TITLE
issue when deleting files

### ISSUE THREAD

**Issue by realwya** [notaapp/talk#399]
When I tried to delete a file, a warning shows "Fail to delete file to Trash" and I have to delete it permanently.
<img width="258" alt="image" src="https://github.com/notaapp/talk/assets/21314132/cb4662ec-4909-4361-b1a8-3f9c7200e086">

**Comment by realwya** [comment]
> This happens when you don't have permission to delete that file. Usually, it occurs on a network drive or syncing service like Dropbox. It can also happen on regular folders with changed permissions. Does any of those ring a bell for your case?

Thanks! Yes, I use a network drive. I will try to figure it out.

**Comment by astoilkov** [comment]
Good.

I'm closing this. If you figure out that this doesn't happen in other apps but happens in Nota you can reopen the issue.
