### ISSUE TITLE
Add a few more zoom steps?

### ISSUE THREAD

**Issue by borekb** [notaapp/talk#7]
On a 4K external monitor that is a bit further away from me (physically), I'd appreciate a few more zoom steps for `Cmd +`.

Currently, the biggest zoom / scale / font size is just about fine enough most of the time but when my eyes are tired and I want to make everything bigger, I'd like to zoom in a bit more.

**Comment by astoilkov** [comment]
During the last year, we added more zoom steps.

I am closing this. @borekb, let me know if you still want more zoom steps.

**Comment by borekb** [comment]
I'm currently using Font Size **20** which is the current maximum. I'd personally bump it to somewhere around 22 – that already pretty large but there are use cases for it, like some colleague standing behind me and wanting to read the text; for that, the current size limit is still on the small side.

**Comment by astoilkov** [comment]
We added more zoom steps in the latest 0.36 release. Closing this issue.

**Comment by borekb** [comment]
Thanks for that. The "font size" doesn't affect preview, right? I still wonder if full UI zoom like in VSCode would be something you would consider – when I want larger text, there's also a good chance I want larger preview, larger file names in the sidebar etc.

**Comment by astoilkov** [comment]
> The "font size" doesn't affect preview, right?

No. It doesn't. But I think it probably should. Will ask @erusev about that.

> I still wonder if full UI zoom like in VSCode would be something you would consider – when I want larger text, there's also a good chance I want larger preview, larger file names in the sidebar etc.

Maybe an option. "Normal" and "Big" because, otherwise, some of the UI won't look great on all possible values.
