### ISSUE TITLE
Allow `$$` to share line with other content

### ISSUE THREAD

**Issue by darsnack** [notaapp/talk#96]
I get that the require syntax:
```md
Some text
$$
y = ax + b
$$
```
makes sense for inline preview.

In my case, I use Pandoc a lot to write in Markdown then output LaTeX. Here, the following syntax is used for labeling equations:
```md
Some text
$$
y = ax + b
$$ {#eq:my-equation}
```
The trailing label breaks highlighting and inline preview (see below).

<img width="704" alt="Screen Shot 2021-08-23 at 12 10 54 PM" src="https://user-images.githubusercontent.com/4811350/130488621-f4dc272c-1cd4-4d7c-b810-b28976ba8dbd.png">

Could leading/trailing content be allowed before/after the opening/closing `$$`, respectively? Even better would be to hide this content when not editing the block!

**Comment by erusev** [comment]
> Could leading/trailing content be allowed before/after the opening/closing $$, respectively?

Yes! This is on the roadmap.

> Even better would be to hide this content when not editing the block!

We'll consider it, thanks for the suggestion.

**Comment by darsnack** [comment]
Any updates on this?

**Comment by astoilkov** [comment]
We haven't implemented this yet. Is this blocking you from using the app?

**Comment by darsnack** [comment]
As soon as I have a single labeled equation in a file, the rest of the file is rendered as a code block (see the second screenshot above). Because of this, I am using iA writer instead.

I don't need the equation labeling to be supported for the app to be usable, just a minimal bug fix for the rendering of the rest of the note. Even if the equation fails to render inline, as long as the rest of the note is not affected, then I can use the app and wait for a more comprehensive feature.

**Comment by erusev** [comment]
@darsnack Is there a spec where we can see what we should be allowed after the fences (`$$`)? Thanks!

**Comment by darsnack** [comment]
The `{#id .class key=val ...}` pattern is standard across Pandoc extensions. So, I guess you would expect a single set of `{}` with text between. The specific extension spec that pertains to my issue with equations is [here](https://github.com/tomduck/pandoc-eqnos).

**Comment by erusev** [comment]
Thanks! One last thing, do you know any apps (or app extensions) that handle this well? Might be useful to see how it works there.

**Comment by darsnack** [comment]
No, I haven't encountered any. I think probably the result that will please most users is to have the trailing `{}` hidden when rendering the equation. Below is how iA Writer handles this which isn't perfect, but definitely acceptable.

<img width="522" alt="Screen Shot 2022-03-12 at 10 04 59 AM" src="https://user-images.githubusercontent.com/4811350/158025419-826826ee-2112-41c2-848d-aa5aa9d99e5d.png">

**Comment by erusev** [comment]
Thanks! Btw, I just noticed that in iA, math expressions won't render unless the `$$` is on the same line as the expression. Do you know if this is a more common syntax?

**Comment by darsnack** [comment]
For anyone coming LaTeX, having `$$` on the same line as the expression will be the more familiar syntax. Technically, both ways are valid for LaTeX and engines like Pandoc accept both. I have grown to prefer the Nota way, because it visually separates the equation even in markdown mode without inserting a new paragraph.

**Comment by erusev** [comment]
Thanks! I'll see if we can add support for this as well (same-line blocks). 

Back to labeling, how common is it to have labels after the opening `$$`? The examples in the repo that you referenced seem to have their labels after the closing `$$`.

Thanks!

**Comment by darsnack** [comment]
Sorry for the slow response. It's not possible to have a label after the opening brace, since `$$` on separate lines vs. same lines are equivalent. Anything after the opening `$$` is considered "math" until the closing `$$`.

Since this feature is on the plan now, I should add that the `{#id ...}` labelling syntax extends to more than just equations. They can be used for figures or tables as well: https://github.com/tomduck/pandoc-xnos (see below). Nota currently handles these cases by just displaying the plain text which I think works. But I did want to mention this in case it affects any implementation decisions.

```
![My image caption.](/an-image.png) {#fig:image widht=75%}

| Column A | Column B      |
|:---------|:--------------|
| Some val | Some other val|

Table: My table caption. {#tab:table}
```

**Comment by erusev** [comment]
Thanks for expanding on this! We'll ship support for attribute blocks for math (after the closing `$$`), and we'll look into adding support for other block types as well. Thanks for the suggestion!

**Comment by astoilkov** [comment]
This is now part of the 0.35 release. Closing this issue. Thank you for all the information and feedback. Appreciate it!
